# Config template for py_ballisticcalc

title = "standard py_ballisticcalc config template"
version = "2.1.1b1"

[pybc.preferred_units]
angular = 'Degree'
distance = 'Yard'
velocity = 'FPS'
pressure = 'InHg'
temperature = 'Fahrenheit'
diameter = 'Inch'
length = 'Inch'
weight = 'Grain'
adjustment = 'Mil'
drop = 'Inch'
energy = 'FootPound'
ogw = 'Pound'
sight_height = 'Inch'
target_height = 'Inch'
twist = 'Inch'
