site_name: py-ballisticcalc
site_description: LGPL library for small arms ballistic calculations based on point-mass (3 DoF) plus spin drift.
edit_uri: edit/main/docs/
site_url: https://o-murphy.github.io/py-ballisticcalc/

nav:
- Get started:
  - Welcome: index.md
#  - Why use py-balllisticcalc: why.md
  - Help: help.md
  - Installation: install.md
  - QuickStart: quick-start.md
#  - Version policy: version-policy.md
  - Contributing: contributing.md
#  - Changelog: changelog.md
- Concepts:
#  - Classes: concepts/classes.md
    - Munition:
#        - concepts/munition/index.md
        - "ðŸ”« Weapon": concepts/munition/weapon.md  # <-- Added a dummy sub-level
        - "ðŸ’£ Ammo": concepts/munition/ammo.md
    - DragModel: concepts/drag_model.md
    - Conditions:
        - "ðŸŒ¡ï¸ Atmo": concepts/conditions/atmo.md
        - "ðŸ’¨ Wind": concepts/conditions/wind.md
        - "ðŸŽ¯ Shot": concepts/conditions/shot.md
    - Units and Dimensions:
#        - DSL:
        - "ðŸ“ Unit": concepts/unit.md
#        - AbstractUnit:
#        - Distance:
#        - Velocity:
#        - Angular:
#        - Pressure:
#        - Temperature:
#        - Weight:
#        - Energy:
    - TrajectoryData: concepts/trajectory_data.md
    - Vector: concepts/vector.md
    - Constants: concepts/constants.md
#    - Interface:
    - Engines:
        - "âš™ï¸ Engines": concepts/engines.md
#    - Logger: concepts/logger.md
#  - Performance:
- API Documentation:
    - Units:
      - Unit System: api/unit.md
    - Munition:
      - Weapon: api/munition/weapon.md
      - Ammo: api/munition/ammo.md
    - DragModel: api/drag_model.md
    - Conditions:
      - Atmo: api/conditions/atmo.md
      - Wind: api/conditions/wind.md
      - Shot: api/conditions/shot.md
    - TrajectoryData: api/trajectory_data.md
    - Constants: api/constants.md
    - Vector: api/vector.md
#    - Interface:
  #    - Engines: api/engines.md
#    - Logger: api/logger.md
- Internals:
  - Architecture: internals/architecture.md
  - Developer Details: internals/details.md
  - Cython Notes: internals/cython.md
- Contributors: contributors.md
- About: about.md

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: teal
    toggle:
      icon: material/lightbulb-auto-outline
      name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
#    - navigation.sections
#    - navigation.path
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  logo: 'favicon.svg'
  favicon: 'favicon.svg'

repo_name: o-murphy/py_ballisticcalc
repo_url: https://github.com/o-murphy/py_ballisticcalc
extra:
  version:
    provider: mike
#    alias: true
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css:
  - 'extra/terminal.css'
  - 'extra/tweaks.css'
extra_javascript:
  - 'extra/feedback.js'
#  - 'extra/fluff.js'
  - 'https://samuelcolvin.github.io/mkdocs-run-code/run_code_main.js'

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true

#hooks:
#- 'docs/plugins/main.py'

#watch:
#  - py_ballisticcalc

plugins:
#- social
- mike:
    alias_type: symlink
    canonical_version: latest
- search
- exclude:
    glob:
      - theme/announce.html
      - plugins/*
      - __pycache__/*
      - why.md
      - version-policy.md
      - changelog.md
      - concepts/classes.md
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          show_source: true
          members_order: source
          separate_signature: true
          filters: ["!^_"]
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true

          docstring_section_style: table
        inventories:
          - url: https://docs.python.org/3/objects.inv
            domains: [py, std]